package com.example.otams;

import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Button;

import com.google.firebase.Timestamp;
import com.google.firebase.auth.FirebaseAuth; //access the signed users
import com.firebase.ui.firestore.FirestoreRecyclerAdapter; //data set to recycleview
import com.firebase.ui.firestore.FirestoreRecyclerOptions;
import com.google.firebase.firestore.FirebaseFirestore; //date within db
import com.google.firebase.firestore.Query;

/**
 * Auto-generated by Android Studio.
 * Needs to be edited.
 */
public class SessionsFragment extends Fragment {

    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_TUTOR_ID = "tutorID";
    private static final String ARG_SESSION_TYPE = "sessionType";

    // TODO: Rename and change types of parameters
    private String tutorID;
    private String sessionType;

    public SessionsFragment() {
        // Empty public construct.
    }
    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param //param1 Parameter 1.
     * @param //param2 Parameter 2.
     * @return A new instance of fragment SessionsFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static SessionsFragment newInstance(String tutorId, String sessionType) {
        //Creating a fragment w args
        SessionsFragment fragment = new SessionsFragment();
        //Its container that has keyvalues
        Bundle args = new Bundle();
        //Arg under parm1/parm2 and sets data to the fragment instance
        args.putString(ARG_TUTOR_ID, tutorId);
        args.putString(ARG_SESSION_TYPE, sessionType);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //Retrieving data
        if (getArguments() != null) {
            tutorID = getArguments().getString(ARG_TUTOR_ID);
            sessionType = getArguments().getString(ARG_SESSION_TYPE);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View viewInflater = inflater.inflate(R.layout.fragment_sessions, container, false);
        //upcoming + past
        RecyclerView upcoming = viewInflater.findViewById(R.id.upcomingSessionsRecyclerView);
        RecyclerView past = viewInflater.findViewById(R.id.pastSessionsRecyclerView);
        //Layout managers
        upcoming.setLayoutManager(new LinearLayoutManager(getContext()));
        past.setLayoutManager(new LinearLayoutManager(getContext()));
        //Database
        FirebaseFirestore database = FirebaseFirestore.getInstance();
        FirebaseAuth authentication = FirebaseAuth.getInstance();

        String newTutor = tutorID;
        if (newTutor == null && authentication.getCurrentUser() != null){
            newTutor = authentication.getCurrentUser().getUid();
        }
        Timestamp now = Timestamp.now();
        Query upcomingQ = database.collection("Sessions").whereEqualTo("tutorId", newTutor).whereGreaterThan("Session Date", now).orderBy("Session Date", Query.Direction.ASCENDING);

        Query pastQ = database.collection("Sessions").whereEqualTo("tutorId", newTutor).whereLessThan("Session Date", now).orderBy("Session Date", Query.Direction.DESCENDING);

        //Upcoming
        FirestoreRecyclerOptions<Session> sessionOption = new FirestoreRecyclerOptions.Builder<Session>().setQuery(upcomingQ, Session.class).build();
        //Implementation
        FirestoreRecyclerAdapter<Session, SessionView> adapter = new FirestoreRecyclerAdapter<Session, SessionView>(sessionOption) {
            @Override
            protected void onBindViewHolder(@NonNull SessionView holder, int i, @NonNull Session session) {
                bindPastIncomingData(holder, session);
            }

            @Override
            public SessionView onCreateViewHolder(ViewGroup parent, int viewType) {
                View views = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_session, parent, false);
                return new SessionView(views);
            }
        };

        upcoming.setAdapter(adapter);
        adapter.startListening();

        FirestoreRecyclerOptions<Session> pastOption = new FirestoreRecyclerOptions.Builder<Session>().setQuery(pastQ, Session.class).build();

        FirestoreRecyclerAdapter<Session, SessionView> pastAdapt = new FirestoreRecyclerAdapter<Session, SessionView>(pastOption) {
            @Override
            protected void onBindViewHolder(@NonNull SessionView holder, int i, @NonNull Session session) {
                bindPastIncomingData(holder, session);
            }


            @NonNull
            @Override
            public SessionView onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                View views = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_session, parent, false);
                return new SessionView(views);
            }
        };
        past.setAdapter(pastAdapt);
        pastAdapt.startListening();

        return viewInflater;
    }

    private void bindPastIncomingData(SessionView holder, Session session){
        Student student = session.getStudent();

        if (student != null) {
            holder.textStudentName.setText(student.getFirstName() + " " + student.getLastName());
            holder.textCourseCode.setText(student.getProgram());
        } else {
            holder.textStudentName.setText("Student");
            holder.textCourseCode.setText("SEG 2105");
        }

        holder.textTimeSlot.setText(String.valueOf(session.getDate()));
    }
    public static class SessionView extends RecyclerView.ViewHolder{
        TextView textStudentName, textCourseCode, textTimeSlot, textStatus;
        Button buttonReject;

        public SessionView (View item){
            super(item);
            textStudentName = item.findViewById(R.id.textStudentName);
            textCourseCode = item.findViewById(R.id.textCourseCode);
            textTimeSlot = item.findViewById(R.id.textTimeSlot);
            textStatus = item.findViewById(R.id.textStatus);
            buttonReject = item.findViewById(R.id.buttonReject);
        }
    }

}